#!/bin/sh -f

bush_home=../../../../softinex/bush

. ${bush_home}/args
. ${bush_home}/ourex_header

libname=MEMPHYSCore

build_shlib=no

if [ ${build_compile} = "yes" ] ; then

build_use_wroot=yes    
if [ ${build_use_wroot} = yes ] ; then    
  cppflags="${cppflags} -DAPP_USE_INLIB_WROOT"
  use_exlib=yes
  use_zlib=yes
  . ${bush_home}/use/exlib
  . ${bush_home}/use/zlib
fi

build_use_aida=yes    
if [ ${build_use_aida} = yes ] ; then    
  cppflags="${cppflags} -DAPP_USE_AIDA"
  use_AIDA=yes
  . ${bush_home}/use/AIDA
fi    
    
cppfiles=
cppfiles="${cppfiles} ../source/Analysis.cxx"
cppfiles="${cppfiles} ../source/DetectorConstruction.cxx"
cppfiles="${cppfiles} ../source/DetectorMessenger.cxx"
cppfiles="${cppfiles} ../source/EventAction.cxx"
cppfiles="${cppfiles} ../source/PhysicsList.cxx"
cppfiles="${cppfiles} ../source/PhysicsMessenger.cxx"
cppfiles="${cppfiles} ../source/PrimaryGeneratorAction.cxx"
cppfiles="${cppfiles} ../source/PrimaryGeneratorMessenger.cxx"
cppfiles="${cppfiles} ../source/RunAction.cxx"
cppfiles="${cppfiles} ../source/RunActionMessenger.cxx"
cppfiles="${cppfiles} ../source/StackingAction.cxx"
cppfiles="${cppfiles} ../source/SteppingAction.cxx"
cppfiles="${cppfiles} ../source/TrackInformation.cxx"
cppfiles="${cppfiles} ../source/TrackingAction.cxx"
cppfiles="${cppfiles} ../source/TrackingActionMessenger.cxx"
cppfiles="${cppfiles} ../source/Trajectory.cxx"
cppfiles="${cppfiles} ../source/WCDigi.cxx"
cppfiles="${cppfiles} ../source/WCDigitizer.cxx"
cppfiles="${cppfiles} ../source/WCHit.cxx"
cppfiles="${cppfiles} ../source/WCSD.cxx"

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

use_inlib=yes
use_geant4=yes

. ${bush_home}/use/inlib
. ./geant4_82

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

. ${bush_home}/compile

fi # end build_compile
 
if [ ${build_archive} = "yes" ] ; then . ${bush_home}/archive; fi

. ${bush_home}/clean
