#!/bin/sh -f

bush_home=../../../../softinex/bush

#. ${bush_home}/args
build_root=no
build_args=
while test $# -ge 1 ; do
  case $1 in
    -root) build_root=yes;;
     *) build_args="${build_args} $1";;
  esac
  shift
done

if [ ${build_root} = yes ] ; then
  ${bush_home}/check_app root-config 'root-config program not found.'
  has_root=$?
  if [ ${has_root} = 0 ] ; then
    ./build_app_read_plot_ROOT ${build_args}
    ./build_app_all_ROOT       ${build_args}
  fi
  
else

  ./build_lib_MEMPHYSCore   ${build_args}
  ./build_app_sim           ${build_args}
  ./build_app_read_plot     ${build_args}

fi
