#!/bin/sh -f

bush_home=../../../../softinex/bush

. ${bush_home}/args
. ${bush_home}/ourex_header

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
cppflags="${cppflags} -DAPP_USE_INLIB_WROOT"

use_geant4=yes
use_inlib=yes
use_zlib=yes

. ./geant4_82
. ${bush_home}/use/inlib
. ${bush_home}/use/zlib

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////

if [ ${build_visual} = "yes" ] ; then
  libs="${build_path}/MEMPHYSCore.lib ${libs}"
else
  libs="-L${build_path} -lMEMPHYSCore ${libs}"
fi

objs=
app_exe=MEMPHYS_sim
app_src=../applications/sim.cpp

. ${bush_home}/application

. ${bush_home}/clean

