#!/bin/sh -f

# options : -clang_11 -sys_geant4

bush_home=../../../../softinex/bush

. ${bush_home}/args
. ${bush_home}/ourex_header

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////

use_geant4=yes
use_inlib=yes

. ./geant4_82
. ${bush_home}/use/inlib

cppflags="${cppflags} -DAPP_USE_AIDA"
cppflags="${cppflags} -DAPP_USE_INLIB_WROOT"

enforce_archive=yes

if [ ${enforce_archive} = yes ] ; then
  # enforce to link the app with the CERN-ROOT format writer driver (BatchLab/Rio) :
  cppflags="${cppflags} -DAPP_USE_ARCHIVE"    
  osc_home=../../../../softinex/osc
  cppflags="${cppflags} -I${osc_home}/Slash"
  cppflags="${cppflags} -I${osc_home}/Lib/include"
  cppflags="${cppflags} -I${osc_home}/amanip/src/cpp"
  cppflags="${cppflags} -I${osc_home}/Minuit"
  cppflags="${cppflags} -I${osc_home}/BatchLab"
  libs="${libs} ${osc_home}/BatchLab/mgr/${build_dir}/libBatchLabAIDA.a"
  libs="${libs} ${osc_home}/Minuit/mgr/${build_dir}/libosc_Minuit.a"
  libs="${libs} ${osc_home}/BatchLab/mgr/${build_dir}/libBatchLabRio.a"
  libs="${libs} ${osc_home}/Lib/mgr/${build_dir}/libLibUtils.a"
  libs="${libs} ${osc_home}/Rio/mgr/${build_dir}/libosc_Rio.a"
  use_exlib=yes
  use_AIDA=yes
  use_zlib=yes
  use_dl=yes
  . ${bush_home}/use/exlib
  . ${bush_home}/use/AIDA
  . ${bush_home}/use/zlib
  . ${bush_home}/use/dl
else
  if [ "`uname -n | grep iridium.lunarc.lu.se`" != "" ] ; then
    osc_home=/nfs/users/gbarrand/usr/local
  else
    osc_home=/usr/local
  fi
  cppflags="${cppflags} -I${osc_home}/osc_batch/17.1/Resources/AIDA/src/cpp"
  libs="${libs} -L${osc_home}/osc_batch/17.1/lib"
  libs="${libs} -lBatchLabAIDA -lLibUtils -lourex_zlib -losc_Minuit -ldl"
fi

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////

if [ ${build_visual} = "yes" ] ; then
  libs="${build_path}/MEMPHYSCore.lib ${libs}"
else
  libs="-L${build_path} -lMEMPHYSCore ${libs}"
fi

objs=
app_exe=MEMPHYS_sim
app_src=../applications/sim.cxx

. ${bush_home}/application

. ${bush_home}/clean

