#!/bin/sh -f

bush_home=../../../../softinex/bush

inlib_home="${bush_home}/../inexlib/inlib"

save_dir=`pwd`

inlib_app=./inlib_wroot_trees
c++ -o ${inlib_app} -I${inlib_home} ${inlib_home}/apps/wroot_trees.cpp
use_status=$?;if [ ${use_status} != 0 ] ; then exit ${use_status};fi

#//////////////////////////////////////////////////////////////
#// Event : ///////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////
script="int eventId, inputEvtId, interMode, vtxVol, " 
script="${script} double[] vtxPos, "
script="${script} int nPart, leptonIndex, protonIndex, "
script="${script} ITuple track = { int pId, parent, float timeStart, "
script="${script}                  double[] direction, "
script="${script}                  double mass, pTot, ETot, "
script="${script}                  double[] momentum, "
script="${script}                  double[] startPos, "
script="${script}                  double[] stopPos, "
script="${script}                  int startVol, stopVol "
script="${script}                }, "
script="${script} int nHits, ITuple hit = { int tubeId, int totalPE, float[] pe}, "
script="${script} int nDigits, double sumPE, ITuple digit = { int tubeId, double pe, time }"

#echo ${script}

name=Event
title='MEMPHYS WC Event'
file="${name}_tree"

#${inlib_app} -script="${script}"
#exit

${inlib_app} -script="${script}" -name=${name} -h    >& ../MEMPHYS/${file}_h.icc
${inlib_app} -script="${script}" -name=${name} -zero >& ../source/${file}_zero.icc
${inlib_app} -script="${script}" -name=${name} -title="${title}" -icc  >& ../source/${file}_create.icc

#//////////////////////////////////////////////////////////////
#// Geometry : ////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////
script="double wcRadius, wcLength, double[] wcOffset, "
script="${script}  double pmtRadius, int nPMTs,  "
script="${script}  ITuple pmtInfos = { "
script="${script}                      int pmtId, pmtLocation, "
script="${script}                      double[] pmtOrient, "
script="${script}                      double[] pmtPosition "
script="${script}                    }"
  
name=Geometry
title='MEMPHYS WC Geometry'
file="${name}_tree"

${inlib_app} -script="${script}" -name=${name} -h    >& ../MEMPHYS/${file}_h.icc
${inlib_app} -script="${script}" -name=${name} -zero >& ../source/${file}_zero.icc
${inlib_app} -script="${script}" -name=${name} -title="${title}" -icc  >& ../source/${file}_create.icc

#//////////////////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////
/bin/rm -f ${inlib_app}
