#!/bin/sh -f

. ./find_bush

inlib_home="${bush_home}/../inexlib/inlib"
exlib_home="${bush_home}/../inexlib/exlib"
ourex_home="${bush_home}/../inexlib/ourex"

app=MEMPHYS
version="`${bush_home}/app_vers MEMPHYS`"

save_dir=`pwd`

cd ..

inlib_incs=./inlib_incs
c++ -o ${inlib_incs} ${inlib_home}/apps/incs.cpp
use_status=$?;if [ ${use_status} != 0 ] ; then exit ${use_status};fi

to=/tmp/${app}
/bin/rm -R -f /tmp/${app}
/bin/rm -f /tmp/${app}_source-${version}.zip

/bin/mkdir -p ${to}

#verbose=-verbose

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#dirs=./inexlib/inlib:./inexlib/exlib
#dirs=../../../softinex/inexlib/inlib:../../../softinex/inexlib/exlib
dirs=${inlib_home}:${exlib_home}

nos='exlib/cbk/wall:wall_client'

${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to}/MEMPHYS ./applications/sim.cpp
${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to}/MEMPHYS ./applications/read_plot.cpp

${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to}/MEMPHYS ./applications/read_plot_ROOT.cpp
${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to}/MEMPHYS ./applications/all_ROOT.cpp
${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to}/MEMPHYS ./applications/geom_ROOT.cpp

${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to} ${bush_home}/cpp/platform.cpp
${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to} ${bush_home}/visual/windef.c

/bin/rm -f ${inlib_incs}

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
find ${to}/MEMPHYS/Users -name 'inexlib' -exec /bin/mv {} ${to}/. \;
/bin/rm -R ${to}/MEMPHYS/Users
find ${to}/Users -name 'bush' -exec /bin/mv {} ${to}/. \;
/bin/rm -R ${to}/Users

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
/bin/cp -R ./source ${to}/MEMPHYS/.
/bin/cp -R ./MEMPHYS ${to}/MEMPHYS/.
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
/bin/cp -R ${bush_home} ${to}/.
#/bin/cp ${bush_home}/app_README ${to}/README

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
/bin/mkdir -p ${to}/inexlib/ourex

items=
items="${items} glutess freetype jpeg png csz expat gl2ps zlib"
for item in ${items} ; do
  /bin/cp -R ${ourex_home}/${item} ${to}/inexlib/ourex/.
done

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////

/bin/cp -R ./mgr     ${to}/${app}/.
/bin/cp -R ./scripts ${to}/${app}/.
/bin/cp -R ./exa_run ${to}/${app}/.
/bin/cp -R ./doc     ${to}/${app}/.

/bin/mkdir -p ${to}/inexlib/inlib
/bin/mkdir -p ${to}/inexlib/exlib

/bin/cp -R -f ${inlib_home}/mgr ${to}/inexlib/inlib/.
/bin/cp -R -f ${exlib_home}/mgr ${to}/inexlib/exlib/.

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
${bush_home}/find_rm ${to} 'bin_*'
${bush_home}/find_rm ${to} 'CVS'
${bush_home}/find_rm ${to} '.git'
${bush_home}/find_rm ${to} '.DS_Store'
${bush_home}/find_rm ${to} 'DerivedData'
${bush_home}/find_rm ${to} 'out*_log'
${bush_home}/find_rm ${to} 'err*_log'
${bush_home}/find_rm ${to} 'out*.log'
${bush_home}/find_rm ${to} 'out*.fits'
${bush_home}/find_rm ${to} 'out*.ps'
${bush_home}/find_rm ${to} 'out*.root'
${bush_home}/find_rm ${to} '*.o'
${bush_home}/find_rm ${to} 'term_*.hist'
${bush_home}/find_rm ${to} 'secure.properties'

/bin/rm -f ${to}/${app}/mgr/inlib_platform

${bush_home}/find_rm ${to}/${app}/mgr '*.zip'

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
cd ${to}/${app}/mgr
cd /tmp
zip -qr ./${app}_source-${version}.zip ${app}

cd ${save_dir}
