#!/bin/sh -f

app="`${exlib_mgr}/app_name`"
version="`${exlib_mgr}/app_vers`"

save_dir=`pwd`

cd ../..

inlib_mgr=./inexlib/inlib/mgr
inlib_incs=./inlib_incs
c++ -o ${inlib_incs} -I${inlib_mgr}/.. ${inlib_mgr}/../apps/incs.cpp
#exit

to=/tmp/${app}
/bin/rm -R -f /tmp/${app}
/bin/rm -f /tmp/${app}_source-${version}.zip

/bin/mkdir -p ${to}

#verbose=-verbose

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
dirs=./inexlib/inlib:./inexlib/exlib

${inlib_incs} ${verbose} -pack -dirs=${dirs} -to=${to} ./${app}/X11/main.cpp
${inlib_incs} ${verbose} -pack -dirs=${dirs} -to=${to} ./${app}/Windows/main.cpp

${inlib_incs} ${verbose} -pack -dirs=${dirs} -to=${to} ./${app}/NativeAndroid/jni/main.cpp
${inlib_incs} ${verbose} -pack -dirs=${dirs} -to=${to} ./${app}/Cocoa/main.mm
${inlib_incs} ${verbose} -pack -dirs=${dirs} -to=${to} ./${app}/Cocoa/GLView.mm
${inlib_incs} ${verbose} -pack -dirs=${dirs} -to=${to} ./${app}/iOS/Classes/GLView.mm

#exit
${inlib_incs} ${verbose} -pack -dirs=${dirs} -to=${to} ./inexlib/inlib/apps/platform.cpp

/bin/rm -f ${inlib_incs}
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
/bin/mkdir -p ${to}/inexlib/ourex

items="mgr"
items="${items} glutess freetype jpeg png csz expat gl2ps zlib zip"
items="${items} cfitsio hdf5 graphviz SOPHYA dcmtk"
for item in ${items} ; do
  /bin/cp -R ./inexlib/ourex/${item} ${to}/inexlib/ourex/.
done

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////

/bin/cp -R ./${app}/mgr ${to}/${app}/.
/bin/cp -R ./${app}/res ${to}/${app}/.
/bin/cp -R ./${app}/comres ${to}/${app}/.

/bin/cp -R ./${app}/NativeAndroid ${to}/${app}/.

/bin/cp ./inexlib/exlib/exlib/app/Android/Native_Main_java ${to}/inexlib/exlib/exlib/app/Android/.

/bin/cp -R ./${app}/Cocoa ${to}/${app}/.
/bin/cp -R ./${app}/iOS ${to}/${app}/.

/bin/cp -R ./inexlib/inlib/mgr ${to}/inexlib/inlib/.
/bin/cp -R ./inexlib/exlib/mgr ${to}/inexlib/exlib/.

/bin/cp ./inexlib/exlib/exlib/yacc/cexpr_lexer.cpp ${to}/inexlib/exlib/exlib/yacc/.
/bin/cp ./inexlib/exlib/exlib/yacc/cexpr_eval.cpp ${to}/inexlib/exlib/exlib/yacc/.
/bin/cp ./inexlib/exlib/exlib/yacc/cexpr_tokens ${to}/inexlib/exlib/exlib/yacc/.

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////

${inlib_mgr}/find_rm ${to} 'bin_*'
${inlib_mgr}/find_rm ${to} 'CVS'
${inlib_mgr}/find_rm ${to} '.git'
${inlib_mgr}/find_rm ${to} '.DS_Store'

/bin/rm -R -f ${to}/${app}/NativeAndroid/bin
/bin/rm -R -f ${to}/${app}/NativeAndroid/gen
/bin/rm -R -f ${to}/${app}/NativeAndroid/libs
/bin/rm -R -f ${to}/${app}/NativeAndroid/obj

/bin/rm -R -f ${to}/${app}/Cocoa/build
/bin/rm -R -f ${to}/${app}/Cocoa/${app}.xcodeproj/project.xcworkspace
/bin/rm -R -f ${to}/${app}/Cocoa/${app}.xcodeproj/xcuserdata

/bin/rm -R -f ${to}/${app}/iOS/build
/bin/rm -R -f ${to}/${app}/iOS/${app}.xcodeproj/project.xcworkspace
/bin/rm -R -f ${to}/${app}/iOS/${app}.xcodeproj/xcuserdata
/bin/rm -f ${to}/${app}/iOS/app_store/distrib_adhoc_${app}_1_0.mobileprovision

/bin/rm -f ${to}/${app}/mgr/out.log
/bin/rm -f ${to}/${app}/mgr/inlib_platform

${inlib_mgr}/find_rm ${to}/${app}/mgr '*.zip'

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
cd ${to}/${app}/mgr
cd /tmp
zip -qr ./${app}_source-${version}.zip ${app}

cd ${save_dir}
