#!/bin/sh -f

c++ -o ./wrap_exe -I.. ../apps/wrap.cpp
use_status=$?;if [ ${use_status} != 0 ] ; then exit ${use_status};fi

find ../inlib/WebGL -name 'wrap_*' -exec /bin/rm -f {} \;

find ../inlib/WebGL -name '*.js' -print > tmp_0
find ../inlib/WebGL -name '*.js.map' -print >> tmp_0
for file in $(cat tmp_0) ; do
  name=`basename ${file}`
  name=`echo ${name} | sed -e 's:\.:\_:g' | sed -e 's:\-:\_:g'`
  #echo "${name}"
  ./wrap_exe ${file} ../inlib/WebGL/wrap_${name}
done
/bin/rm -f tmp_0 wrap_exe

