#!/bin/sh -f

. ./find_bush

. ./args

. ${bush_home}/ourex_header

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
cppflags="${cppflags} -DINLIB_USE_CSZ"

use_exlib=yes
use_inlib=yes
use_csz=yes
use_freetype=yes
use_png=yes
use_zip=yes
use_zlib=yes
use_gl2ps=yes

. ${bush_home}/use/exlib
. ${bush_home}/use/inlib
. ${bush_home}/use/csz
. ${bush_home}/use/freetype
. ${bush_home}/use/png
. ${bush_home}/use/zip
. ${bush_home}/use/zlib
. ${bush_home}/use/gl2ps

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////

objs=
app_exe=MEMPHYS_read_plot_offscreen
app_src=../applications/read_plot_offscreen.cpp

. ${bush_home}/application

. ${bush_home}/clean

