#!/bin/sh -f

. ./find_bush

. ${bush_home}/args
. ${bush_home}/g4args

#//////////////////////////////////////
#/// specific args : //////////////////
#//////////////////////////////////////
build_use_lib_core=no
items="${build_args}"
build_args=
for item in ${items} ; do
  if [ ${item} = "-core" ] ; then
    build_use_lib_core=yes
  else
    build_args="${build_args} ${item}"
  fi
done

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
. ${bush_home}/ourex_header

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
cppflags="${cppflags} -DAPP_USE_INLIB_WROOT"

if [ ${build_visual} = "yes" ] ; then
  cppflags="${cppflags} -I../MEMPHYS -I../source" # to bypass "../MEMPHYS/Analysis.h" not found (because MEMPHYS is uppercase).
fi

use_exlib=yes

use_geant4=yes
use_inlib=yes
use_zlib=yes
use_socket=yes

. ./use_geant4

. ${bush_home}/use/exlib
. ${bush_home}/use/inlib
. ${bush_home}/use/zlib
. ${bush_home}/use/socket

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

sim_src="../source"
/bin/rm -f ./tmp_0
find ${sim_src} -name '*.cpp' -print > ./tmp_0
grep -v 'PhysicsList_' ./tmp_0 > ./tmp_1
for file in $(cat ./tmp_1) ; do cppfiles="${cppfiles} ${file}";done
/bin/rm -f ./tmp_0 ./tmp_1

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////

objs=
app=MEMPHYS_sim
app_exe=MEMPHYS_sim
app_src=../applications/sim.cpp

. ${bush_home}/application

. ${bush_home}/clean

