#!/bin/sh -f

. ./find_bush

. ./args

. ${bush_home}/ourex_header

libname=MEMPHYSCore

build_shlib=no

if [ ${build_compile} = "yes" ] ; then

build_use_wroot=yes    
if [ ${build_use_wroot} = yes ] ; then    
  cppflags="${cppflags} -DAPP_USE_INLIB_WROOT"
  use_exlib=yes
  use_zlib=yes
  . ${bush_home}/use/exlib
  . ${bush_home}/use/zlib
fi

cppfiles=

cppfiles="${cppfiles} ../source/PhysicsList.cpp"
cppfiles="${cppfiles} ../source/Analysis.cpp"
cppfiles="${cppfiles} ../source/DetectorConstruction.cpp"
cppfiles="${cppfiles} ../source/DetectorMessenger.cpp"
cppfiles="${cppfiles} ../source/EventAction.cpp"
cppfiles="${cppfiles} ../source/PhysicsMessenger.cpp"
cppfiles="${cppfiles} ../source/PrimaryGeneratorAction.cpp"
cppfiles="${cppfiles} ../source/PrimaryGeneratorMessenger.cpp"
cppfiles="${cppfiles} ../source/RunAction.cpp"
cppfiles="${cppfiles} ../source/RunActionMessenger.cpp"
cppfiles="${cppfiles} ../source/StackingAction.cpp"
cppfiles="${cppfiles} ../source/SteppingAction.cpp"
cppfiles="${cppfiles} ../source/TrackInformation.cpp"
cppfiles="${cppfiles} ../source/TrackingAction.cpp"
cppfiles="${cppfiles} ../source/TrackingActionMessenger.cpp"
cppfiles="${cppfiles} ../source/Trajectory.cpp"
cppfiles="${cppfiles} ../source/WCDigi.cpp"
cppfiles="${cppfiles} ../source/WCDigitizer.cpp"
cppfiles="${cppfiles} ../source/WCHit.cpp"
cppfiles="${cppfiles} ../source/WCSD.cpp"

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

use_inlib=yes
use_geant4=yes

. ./use_geant4

. ${bush_home}/use/inlib

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

. ${bush_home}/compile

fi # end build_compile
 
if [ ${build_archive} = "yes" ] ; then . ${bush_home}/archive; fi

. ${bush_home}/clean
