#!/bin/sh -f

. ./find_bush

. ${bush_home}/args
. ${bush_home}/g4args

#//////////////////////////////////////
#//////////////////////////////////////
#//////////////////////////////////////

. ${bush_home}/ourex_header

/bin/rm -R -f ${build_path}/distrib/MEMPHYS

version="`${bush_home}/app_vers`"
  
install_dir="${build_path}/distrib/MEMPHYS/${version}"

/bin/rm -R -f ${install_dir}/bin
/bin/mkdir -p ${install_dir}/bin

apps="MEMPHYS_sim MEMPHYS_read_plot_offscreen"

#if [ ${build_offscreen} = no -a ${build_root} = yes ] ; then
  apps="${apps} MEMPHYS_read_plot MEMPHYS_read_plot_ROOT MEMPHYS_all_ROOT"
#fi

for item in ${apps} ; do  
  if [ ${build_visual} = "yes" ] ; then
    if [ -x ${build_path}/${item}.exe ] ; then
      /bin/cp ${build_path}/${item}.exe ${install_dir}/bin/.
    else
      echo "MEMPHYS/mgr/build : distrib : ${build_path}/${item}.exe not found. Continue."
    fi
    if [ -f ${build_path}/${item}.exe.manifest ] ; then
      /bin/cp ${build_path}/${item}.exe.manifest ${install_dir}/bin/.
    fi
  else
    if [ -x ${build_path}/${item} ] ; then
      /bin/cp ${build_path}/${item} ${install_dir}/bin/.
    else
      echo "MEMPHYS/mgr/build : distrib : ${build_path}/${item} not found. Continue."
    fi      
  fi      
done
    
find . -maxdepth 1 -name 'run*setup.csh' -exec /bin/cp {} ${install_dir}/. \;
find . -maxdepth 1 -name 'run*setup.sh' -exec /bin/cp {} ${install_dir}/. \;
  
find . -maxdepth 1 -name 'gcc_*.csh' -exec /bin/cp {} ${install_dir}/. \;
find . -maxdepth 1 -name 'gcc_*.sh' -exec /bin/cp {} ${install_dir}/. \;
  
/bin/cp cern_root_setup.sh  ${install_dir}/.
/bin/cp cern_root_setup.csh ${install_dir}/.
/bin/cp ../doc/README_for_distrib ${install_dir}/README

/bin/rm -R -f ${install_dir}/res
/bin/mkdir -p ${install_dir}/res
  
/bin/mkdir -p ${install_dir}/res/MEMPHYS/scripts
/bin/cp -R ../scripts/ROOT ${install_dir}/res/MEMPHYS/scripts/.
/bin/cp -R ../scripts/geant4 ${install_dir}/res/MEMPHYS/scripts/.
/bin/cp -R ../scripts/slurm ${install_dir}/res/MEMPHYS/scripts/.

# exa run env :
exa_run_dir="${install_dir}/exa_run"
/bin/mkdir -p ${exa_run_dir}
/bin/cp ../scripts/geant4/init.g4m        ${exa_run_dir}/.
/bin/cp ../scripts/geant4/input.memphys   ${exa_run_dir}/.
/bin/cp ../scripts/geant4/job_options.mac ${exa_run_dir}/.
/bin/cp ../scripts/slurm/sim_slurm        ${exa_run_dir}/.
/bin/cp ../scripts/ROOT/analysis.C        ${exa_run_dir}/.
/bin/cp ../scripts/ROOT/hits.C            ${exa_run_dir}/.

platform=`${bush_home}/platform "${cpp_compiler}"`
if [ "${platform}" = "" ] ; then
  echo "bush/app_distrib : can't guess platform for ${cpp_compiler}."
  exit
fi
  
save_dir=`pwd`
  
${bush_home}/check_app zip 'zip not found, we use tar.'
use_status=$?;
if [ ${use_status} != 0 ] ; then
  cd ${build_path}/distrib
  tar cf MEMPHYS-${version}-${platform}.tar ./MEMPHYS
  cd ${save_dir}
else
  cd ${build_path}/distrib
  zip -qr MEMPHYS-${version}-${platform}.zip ./MEMPHYS
  cd ${save_dir}
fi

