#!/bin/sh -f


. ./find_bush

. ./args

. ${bush_home}/ourex_header

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
cppflags="${cppflags} -DINLIB_USE_CSZ"

use_exlib=yes
use_inlib=yes
use_csz=yes
use_freetype=yes
use_zlib=yes
use_GL=yes

if [ ${build_visual} = "yes" ] ; then
  use_Windows=yes
else
  use_GLX=yes
  use_X11=yes
fi

. ${bush_home}/use/exlib
. ${bush_home}/use/inlib
. ${bush_home}/use/csz
. ${bush_home}/use/freetype
. ${bush_home}/use/zlib
. ${bush_home}/use/GL
. ${bush_home}/use/GLX
. ${bush_home}/use/X11
. ${bush_home}/use/Windows

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////

objs=
app_exe=MEMPHYS_read_plot
app_src=../applications/read_plot.cpp

. ${bush_home}/application

. ${bush_home}/clean

