#!/bin/sh -f

. ./find_bush

. ./args

. ${bush_home}/ourex_header

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
cppflags="${cppflags} -DAPP_USE_INLIB_WROOT"

use_geant4=yes
use_inlib=yes
use_zlib=yes
use_socket=yes

. ./use_geant4

. ${bush_home}/use/inlib
. ${bush_home}/use/zlib
. ${bush_home}/use/socket

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////

if [ ${build_visual} = "yes" ] ; then
  libs="${build_path}/libMEMPHYSCore.a ${libs}"
else
  libs="-L${build_path} -lMEMPHYSCore ${libs}"
fi

objs=
app_exe=MEMPHYS_sim
app_src=../applications/sim.cpp

. ${bush_home}/application

. ${bush_home}/clean

