#!/bin/sh -f

#set -x

#. ./find_bush
bush_home="`pwd`/../../bush"

inlib_home="${bush_home}/../inexlib/inlib"
exlib_home="${bush_home}/../inexlib/exlib"
ourex_home="${bush_home}/../inexlib/ourex"

app="`${bush_home}/app_name`"
version="`${bush_home}/app_vers`"

save_dir=`pwd`

cd ..

inlib_incs=./inlib_incs
c++ -o ${inlib_incs} ${inlib_home}/apps/incs.cpp
use_status=$?;if [ ${use_status} != 0 ] ; then exit ${use_status};fi

to=/tmp/${app}
/bin/rm -R -f /tmp/${app}
/bin/rm -f /tmp/${app}_source-${version}.zip

/bin/mkdir -p ${to}

#verbose=-verbose

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#dirs=./inexlib/inlib:./inexlib/exlib
#dirs=../../../softinex/inexlib/inlib:../../../softinex/inexlib/exlib
dirs=${inlib_home}:${exlib_home}

nos='exlib/cbk/wall:wall_client'

${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to}/${app} ./applications/sim.cpp

${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to}/${app} ./applications/read_plot.cpp
${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to}/${app} ./applications/read_plot_offscreen.cpp

${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to} ${bush_home}/cpp/platform.cpp
${inlib_incs} ${verbose} -pack -dirs=${dirs} -nos=${nos} -to=${to} ${bush_home}/visual/windef.c

/bin/rm -f ${inlib_incs}

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
find ${to}/${app}/Users -name 'inexlib' -exec /bin/mv {} ${to}/. \;
/bin/rm -R ${to}/${app}/Users
find ${to}/Users -name 'bush' -exec /bin/mv {} ${to}/. \;
/bin/rm -R ${to}/Users

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
# missed by inlib_incs :
/bin/cp ${inlib_home}/inlib/svalues ${to}/inexlib/inlib/inlib/.
/bin/cp ${inlib_home}/inlib/pointer ${to}/inexlib/inlib/inlib/.
/bin/mkdir -p ${to}/inexlib/exlib/exlib
/bin/cp ${exlib_home}/exlib/zlib ${to}/inexlib/exlib/exlib/.

/bin/rm -R -f ${to}/inexlib/exlib/exlib/Windows
/bin/rm -R -f ${to}/inexlib/exlib/exlib/yacc

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
/bin/cp -R ./source ${to}/${app}/.
/bin/cp -R ./${app} ${to}/${app}/.

/bin/cp -R ./applications/all_ROOT.cpp       ${to}/${app}/applications/.
/bin/cp -R ./applications/geom_ROOT.cpp      ${to}/${app}/applications/.
/bin/cp -R ./applications/read_plot_ROOT.cpp ${to}/${app}/applications/.

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
/bin/cp -R ${bush_home} ${to}/.
/bin/cp ./doc/README_for_pack ${to}/README

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
/bin/mkdir -p ${to}/inexlib/ourex

items=
#items="${items} glutess freetype jpeg png csz expat gl2ps zlib zip"
items="${items} csz zlib"
for item in ${items} ; do
  /bin/cp -R ${ourex_home}/${item} ${to}/inexlib/ourex/.
done

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////

/bin/cp -R ./mgr     ${to}/${app}/.
/bin/cp -R ./cmake   ${to}/${app}/.
/bin/cp -R ./scripts ${to}/${app}/.
/bin/cp -R ./exa_run ${to}/${app}/.
/bin/mkdir -p ${to}/${app}/doc
/bin/cp ./doc/History ${to}/${app}/doc/.
/bin/cp ./doc/README_for_distrib ${to}/${app}/doc/.

/bin/mkdir -p ${to}/inexlib/inlib
/bin/mkdir -p ${to}/inexlib/exlib

#/bin/cp -R -f ${inlib_home}/mgr ${to}/inexlib/inlib/.
#/bin/cp -R -f ${exlib_home}/mgr ${to}/inexlib/exlib/.

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
${bush_home}/find_rm ${to} 'bin_*'
${bush_home}/find_rm ${to} 'CVS'
${bush_home}/find_rm ${to} '.git'
${bush_home}/find_rm ${to} '.DS_Store'
${bush_home}/find_rm ${to} 'DerivedData'
${bush_home}/find_rm ${to} 'out*_log'
${bush_home}/find_rm ${to} 'err*_log'
${bush_home}/find_rm ${to} 'out*.log'
${bush_home}/find_rm ${to} 'out*.fits'
${bush_home}/find_rm ${to} 'out*.ps'
${bush_home}/find_rm ${to} 'out*.root'
${bush_home}/find_rm ${to} '*.o'
${bush_home}/find_rm ${to} 'term_*.hist'
${bush_home}/find_rm ${to} 'secure.properties'

/bin/rm -f ${to}/${app}/mgr/inlib_platform

${bush_home}/find_rm ${to}/${app}/mgr '*.zip'

#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
#///////////////////////////////////////////////////
cd ${to}/${app}/mgr
cd /tmp
zip -qr ./${app}_source-${version}.zip ${app}

cd ${save_dir}
