#!/bin/sh -f

if [ $# != 1 ] ; then
  echo 'bush/win_run : A path argument is expected.'
  exit
fi

run_args=

path="$1"

path=`cygpath -w -a ${path}`
cmd="${HOME}/PsExec.exe -s -i '${path}' ${run_args}"

eval ${cmd}
