#!/bin/sh -f

search=
if [ $# = 1 ] ; then search=$1; fi

g4exa=/usr/local/geant4/geant4-09-05-ref-00/examples

dirs=
#dirs="${dirs} ${g4exa}/advanced/human_phantom/gdmlData/Male"
#dirs="${dirs} ${g4exa}/advanced/human_phantom/gdmlData/Female"
#dirs="${dirs} ${g4exa}/advanced/ChargeExchangeMC"
dirs="${dirs} ${g4exa}/extended/persistency/gdml/G01"
dirs="${dirs} ${g4exa}/extended/persistency/gdml/G02"
dirs="${dirs} ${g4exa}/extended/persistency/gdml/G03"
dirs="${dirs} ${g4exa}/extended/persistency/gdml/G04"

if [ "${search}" = "" ] ; then

  for dir in ${dirs} ; do
    find ${dir} -name '*.gdml' -print -exec ./bin_clang/gdml_read {} \;
  done

else

  for dir in ${dirs} ; do
    find ${dir} -name '*.gdml' -print -exec grep ${search} {} \;
  done

fi


