#!/bin/sh -f

verbose=no
threads=0

while test $# -ge 1 ; do
  case $1 in
    -v) verbose=yes;;
    -threads_2) threads=2;;
    -threads_3) threads=3;;
    -threads_4) threads=4;;
    -threads_5) threads=5;;
    -threads_6) threads=6;;
    -threads_7) threads=7;;
    -threads_8) threads=8;;
    -*) build_args="${build_args} $1";;
     *) if [ $# = 1 ] ; then what=$1; else echo "unknown option : $1"; fi;;
  esac
  shift
done


where="${HOME}/Documents/TouchSky"
if [ ! -d ${where} ] ; then
  echo "directory ${where} not found."
  exit
fi

bin_dir=
if [ `uname` = "Darwin" ] ; then bin_dir=bin_clang;fi
if [ `uname` = "Linux" ] ; then bin_dir=bin_gnu;fi

#///////////////////////////////////////////////
#// CFHTLS_1 : /////////////////////////////////
#///////////////////////////////////////////////
#name=CFHTLS_1
#scales="2 4 8 16 32"

#///////////////////////////////////////////////
#// sky_40 : ///////////////////////////////////
#///////////////////////////////////////////////
name=sky_40
scales="2 4 8 16 32 64"

#///////////////////////////////////////////////
#// M51_large : ////////////////////////////////
#///////////////////////////////////////////////
#name=M51_large
#scales="2 4 8"

#///////////////////////////////////////////////
#///////////////////////////////////////////////
#///////////////////////////////////////////////
if [ ${verbose} = yes ] ; then echo "${name}";fi

pdir="${name}.proot"

for scale in ${scales} ; do
  #echo "scale ${scale} ..."
  /bin/rm -R -f ${where}/${pdir}/${scale}
  time ./${bin_dir}/proot -scale=${scale} -name=${pdir} -type=float -threads=${threads}
done
