#!/bin/sh -f

save_dir="`pwd`"

cd ../inlib
_find namespace | grep -v inlib | grep -v Found | sort -u | awk '{print $2;}'> ./tmp_0
/bin/mv ./tmp_0 ${save_dir}/namespaces
cd ${save_dir}

for item in $(cat ./namespaces) ; do
  echo "look for ${item} ..."
  cd ../inlib
  _find "class ${item} "
  #| grep class | grep ':' | grep -v '::s_class'
  cd ${save_dir}
done
