CMTPATH=/afs/in2p3.fr/home/throng/lalorsay/contrib
CMT_tag=$(tag)
CMTROOT=/afs/in2p3.fr/home/throng/lalorsay/CMT/v1r18p20061003
CMT_root=/afs/in2p3.fr/home/throng/lalorsay/CMT/v1r18p20061003
CMTVERSION=v1r18p20061003
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/afs/in2p3.fr/home/throng/lalorsay/CMT/v1r18p20061003/${CMTBIN}:/usr/local/root/root_v5.24.00/root/bin:/afs/in2p3.fr/home/b/barrand/v0r0/bin/sh:/afs/in2p3.fr/home/b/barrand/v0r0/bin/Linux:/afs/in2p3.fr/home/b/barrand/v0r0/bin/sh:/afs/in2p3.fr/home/b/barrand/v0r0/bin/Linux:/afs/in2p3.fr/home/b/barrand/v0r0/bin/sh:/afs/in2p3.fr/home/b/barrand/v0r0/bin/Linux:/afs/in2p3.fr/home/b/barrand/v0r0/bin/sh:/afs/in2p3.fr/home/b/barrand/v0r0/bin/Linux:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/afs/in2p3.fr/home/b/barrand/usr/local/valgrind/1.9.5/bin:/afs/in2p3.fr/home/b/barrand/usr/local/valgrind/1.9.5/bin:/afs/in2p3.fr/home/b/barrand/usr/local/valgrind/1.9.5/bin:/afs/in2p3.fr/home/b/barrand/usr/local/valgrind/1.9.5/bin:/afs/in2p3.fr/home/throng/lalorsay/geant4/8.2/x86_64-slc5-gcc412/lib/Linux-g++:/afs/in2p3.fr/home/throng/lalorsay/OpenScientist/osc_vis/16.11.2/x86_64-slc5-gcc412/bin:/usr/local/root/pro/root/root/bin:/afs/in2p3.fr/home/throng/lalorsay/contrib/MEMPHYS/v8r0/slc5_gcc412
CLASSPATH=/afs/in2p3.fr/home/throng/lalorsay/CMT/v1r18p20061003/java
debug_option=-g
cc=gcc
cflags= -O
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=c++
cppflags=-pipe  -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -fPIC -O
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplinkflags= -O
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=${symlink}
build_library_links=true
remove_library_links=true
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -fs 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-slc55-gcc412
MEMPHYS_tag=$(tag)
MEMPHYSROOT=/afs/in2p3.fr/home/throng/lalorsay/contrib/MEMPHYS/v8r0
MEMPHYS_root=/afs/in2p3.fr/home/throng/lalorsay/contrib/MEMPHYS/v8r0
MEMPHYSVERSION=v8r0
MEMPHYS_cmtpath=/afs/in2p3.fr/home/throng/lalorsay/contrib
MEMPHYS_project=lalorsay
MEMPHYS_project_release=contrib
OSC_home=/afs/in2p3.fr/home/throng/lalorsay/OpenScientist/osc_vis/16.11.2/x86_64-slc5-gcc412
OSC_AIDA_home=$(OSC_home)/Resources/AIDA
OSC_AIDA_incs=-I$(OSC_AIDA_home)/src/cpp
OSC_AIDA_linkopts=-L$(OSC_home)/lib -lOnXLabAIDA -lOnXLabCore -lBatchLabCore -losc_Minuit -lMidnight -lHCL -lOnXCore -lLibXML -losc_expat -lLibZip -losc_zip -lz -lLibUtils -ldl
OSC_amanip_home=$(OSC_home)/Resources/amanip
OSC_amanip_incs=-I$(OSC_amanip_home)/src/cpp
OSC_OnX_incs=-I$(OSC_home)/Resources/Slash -I$(OSC_home)/Resources/expat/include -I$(OSC_home)/Resources/Lib/include -I$(OSC_home)/Resources/OnX/include -I$(OSC_home)/Resources/BatchLab -I$(OSC_home)/Resources/OnXLab
OSC_OnX_linkopts=-L$(OSC_home)/lib -lOnXCore -lLibXML -losc_expat -lLibZip -losc_zip -lz -lLibUtils -ldl
OSC_Inventor_incs=-I$(OSC_home)/Resources/CoinGL/include -I$(OSC_home)/Resources/HEPVis/include
OSC_Inventor_linkopts=-L$(OSC_home)/lib -lHEPVisPlotter -lHEPVisDetector -lHEPVisGeometry -lHEPVisUtils  -losc_dvi2bitmap -losc_png -losc_jpeg -losc_freetype2 -losc_Coin -lLibUtils -lGLU -lGL -ldl -L/usr/X11R6/lib -lX11 -lpthread
OSC_G4Lab_incs=-I$(OSC_home)/Resources/G4Lab/include
OSC_G4Lab_linkopts=-L$(OSC_home)/lib -lG4LabUIOnX -lG4LabCore
LD_LIBRARY_PATH=/usr/local/root/root_v5.24.00/root/lib/root:.:/afs/in2p3.fr/home/throng/lalorsay/geant4/8.2/x86_64-slc5-gcc412/lib/Linux-g++:/afs/in2p3.fr/home/throng/lalorsay/OpenScientist/osc_vis/16.11.2/x86_64-slc5-gcc412/lib:/afs/in2p3.fr/home/throng/lalorsay/OpenScientist/osc_vis/16.11.2/x86_64-slc5-gcc412/bin:/usr/local/lhcxx/CLHEP/2.0.4.2/lib:/afs/in2p3.fr/home/throng/lalorsay/contrib/MEMPHYS/v8r0/slc5_gcc412
ONX_SESSION=/afs/in2p3.fr/home/throng/lalorsay/OpenScientist/osc_vis/16.11.2/x86_64-slc5-gcc412/Resources/OnX/scripts/OnX/Session.onx
TTFPATH=/afs/in2p3.fr/home/throng/lalorsay/OpenScientist/osc_vis/16.11.2/x86_64-slc5-gcc412/Resources/HEPVis/fonts
ONXROOT=/afs/in2p3.fr/home/throng/lalorsay/OpenScientist/osc_vis/16.11.2/x86_64-slc5-gcc412/Resources/OnX
ONXLABROOT=/afs/in2p3.fr/home/throng/lalorsay/OpenScientist/osc_vis/16.11.2/x86_64-slc5-gcc412/Resources/OnXLab
G4LABROOT=/afs/in2p3.fr/home/throng/lalorsay/OpenScientist/osc_vis/16.11.2/x86_64-slc5-gcc412/Resources/G4Lab
COIN_DONT_INFORM_INDIRECT_RENDERING=1
CLHEP_home=/usr/local/lhcxx/CLHEP/2.0.4.2
CLHEP_cppflags=-I${CLHEP_home}/include
CLHEP_linkopts=-L${CLHEP_home}/lib -lCLHEP
Geant4_home=/afs/in2p3.fr/home/throng/lalorsay/geant4/8.2/x86_64-slc5-gcc412
Geant4_system=Linux-g++
Geant4_lib_suffix=lib
Geant4_incs=-I${Geant4_home}/include
Geant4_lib=${Geant4_home}/lib/Linux-g++
ROOT_home=/usr/local/root/pro/root
ROOT_include=$(ROOT_home)/include/root
ROOT_lib=$(ROOT_home)/lib/root
ROOT_cppflags=-I$(ROOT_include)
ROOT_Cint_linkopts=-L$(ROOT_lib) -lCint -ldl
ROOT_Core_linkopts=-L$(ROOT_lib) -lCore
ROOT_Matrix_linkopts=-L$(ROOT_lib) -lMatrix
ROOT_Tree_linkopts=-L$(ROOT_lib) -lTree
ROOT_Hist_linkopts=-L$(ROOT_lib) -lHist
ROOT_Graf_linkopts=-L$(ROOT_lib) -lGraf
ROOT_Graf3d_linkopts=-L$(ROOT_lib) -lGraf3d
ROOT_Geom_linkopts=-L$(ROOT_lib) -lGeom
ROOT_Gui_linkopts=-L$(ROOT_lib) -lGui
ROOT_freetype_linkopts=-L$(ROOT_lib) -lfreetype
ROOT_Gpad_linkopts=-L$(ROOT_lib) -lGpad
ROOT_Rint_linkopts=-L$(ROOT_lib) -lRint
ROOT_HistPainter_linkopts=-L$(ROOT_lib) -lHistPainter
ROOTSYS=/usr/local/root/pro/root/root
Platform_bin=${CMTCONFIG}
MEMPHYS_Geant4_incs=${CLHEP_cppflags} ${Geant4_incs}
MEMPHYS_Geant4_linkopts=-L${Geant4_lib} -lG4physicslists -lG4readout -lG4run -lG4event -lG4tracking -lG4processes -lG4digits_hits -lG4track -lG4particles -lG4geometry -lG4graphics_reps -lG4materials -lG4intercoms -lG4global ${CLHEP_linkopts}
MEMPHYSCore_cppflags=${OSC_AIDA_incs} ${MEMPHYS_Geant4_incs}
MEMPHYSCore_linkopts=-L${MEMPHYSROOT}/$(Platform_bin) -lMEMPHYSCore
MEMPHYS_kind=dll
MEMPHYS_cppflags=${OSC_G4Lab_incs} ${OSC_amanip_incs} ${OSC_AIDA_incs} ${OSC_OnX_incs} ${OSC_Inventor_incs}
MEMPHYS_shlibflags=${OSC_Inventor_linkopts} ${OSC_OnX_linkopts}
MEMPHYS_batch_cppflags=${MEMPHYSCore_cppflags}
MEMPHYS_session_cppflags=${MEMPHYS_Geant4_incs} ${MEMPHYS_batch_cppflags}
MEMPHYS_analysis_ROOT_cppflags=${ROOT_cppflags}
MEMPHYS_analysis_aida_ROOT_cppflags=${ROOT_cppflags} ${OSC_AIDA_incs}
DYLD_LIBRARY_PATH=/usr/local/root/root_v5.24.00/root/lib/root
tag=slc5_gcc412
package=MEMPHYS
version=v8r0
PACKAGE_ROOT=$(MEMPHYSROOT)
srcdir=../src
bin=../$(MEMPHYS_tag)/
javabin=../classes/
mgrdir=cmt
project=lalorsay
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin
use_linkopts= $(cmt_installarea_linkopts)   $(MEMPHYS_linkopts) 
lalorsay_installarea_prefix=$(cmt_installarea_prefix)
lalorsay_installarea_prefix_remove=$(lalorsay_installarea_prefix)
use_requirements=requirements $(CMTROOT)/mgr/requirements 
use_includes= 
use_fincludes= $(use_includes)
use_stamps= $(MEMPHYS_stamps) 
use_cflags=  $(MEMPHYS_cflags) 
use_pp_cflags=  $(MEMPHYS_pp_cflags) 
use_cppflags=  $(MEMPHYS_cppflags) 
use_pp_cppflags=  $(MEMPHYS_pp_cppflags) 
use_fflags=  $(MEMPHYS_fflags) 
use_pp_fflags=  $(MEMPHYS_pp_fflags) 
includes= $(ppcmd)"/afs/in2p3.fr/home/throng/lalorsay/contrib/MEMPHYS/v8r0" $(use_includes)
fincludes= $(includes)
MEMPHYSCore_use_linkopts=  $(MEMPHYS_linkopts) 
MEMPHYS_use_linkopts=  $(MEMPHYS_linkopts) 
MEMPHYS_batch_use_linkopts=  $(MEMPHYS_linkopts) 
MEMPHYS_analysis_use_linkopts=  $(MEMPHYS_linkopts) 
MEMPHYS_session_use_linkopts=  $(MEMPHYS_linkopts) 
test_use_linkopts=  $(MEMPHYS_linkopts) 
MEMPHYS_analysis_ROOT_use_linkopts=  $(MEMPHYS_linkopts) 
MEMPHYS_analysis_aida_ROOT_use_linkopts=  $(MEMPHYS_linkopts) 
constituents= MEMPHYSCore MEMPHYS MEMPHYS_batch MEMPHYS_analysis MEMPHYS_session 
all_constituents= $(constituents)
constituentsclean= MEMPHYS_sessionclean MEMPHYS_analysisclean MEMPHYS_batchclean MEMPHYSclean MEMPHYSCoreclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
debug_constituents= test 
debug_constituentsclean= testclean 
ROOT_constituents= MEMPHYS_analysis_ROOT MEMPHYS_analysis_aida_ROOT 
ROOT_constituentsclean= MEMPHYS_analysis_aida_ROOTclean MEMPHYS_analysis_ROOTclean 
