#!/bin/sh -f

if [ $# != 1 ] ; then
  echo "give the name of an app."
  exit
fi

app_dir=`dirname $0`

if [ "${app_dir:0:1}" != "/" ] ; then
  echo "This script must be started with an absolute path."
  exit
fi

bush_home="${app_dir}/../../../bush"
#ls ${bush_home}
#exit

inlib_home=${bush_home}/../inexlib/inlib
exlib_home=${bush_home}/../inexlib/exlib
ourex_home=${bush_home}/../inexlib/ourex

app=$1
echo ${app}

app=`echo ${app} | sed -e 's:\.cpp::g'`
app=`echo ${app} | sed -e 's:\.c::g'`
app=`echo ${app} | sed -e 's:./::g'`

save_dir=`pwd`

inlib_incs=_incs

${bush_home}/check_app _incs '_incs program not found.'
use_status=$?;if [ ${use_status} != 0 ] ; then exit ${use_status};fi

pack_name=${app}

to=/tmp/${pack_name}
/bin/rm -R -f /tmp/${pack_name}

/bin/mkdir -p ${to}
/bin/mkdir -p ${to}/inlib
/bin/mkdir -p ${to}/exlib
/bin/mkdir -p ${to}/ourex

#verbose=-verbose

cd ../..

dirs=./inlib:./exlib

${inlib_incs} ${verbose} -pack -dirs=${dirs} -to=${to} ./exlib/apps/${app}.cpp

if [ ${app} = "repserv" ] ; then
  /bin/cp -R ${ourex_home}/tntnet  ${to}/ourex/.
  /bin/cp -R ${ourex_home}/zlib    ${to}/ourex/.
  /bin/cp -R ${ourex_home}/zip     ${to}/ourex/.
  /bin/cp -R ${ourex_home}/Getline ${to}/ourex/.

  ${inlib_incs} ${verbose} -pack -dirs=${dirs} -to=${to} ./exlib/apps/term_repserv_client.cpp

  /bin/cp ${exlib_home}/mgr/repserv_README ${to}/README
fi

find ${to}/ourex -name 'bin_*' -print > tmp_0
for file in $(cat tmp_0) ; do /bin/rm -R -f ${file}; done
/bin/rm -f tmp_0

/bin/cp -R ${bush_home} ${to}/.
/bin/rm -R -f ${to}/bush/.git

#/bin/cp ${inlib_home}/inlib/mathd ${to}/inlib/inlib/.

/bin/mkdir -p ${to}/exlib/mgr
/bin/cp ${exlib_home}/mgr/build ${to}/exlib/mgr/.

chmod a+x ${to}/exlib/mgr/build

#if [ ! -f ${to}/README ] ; then
#  /bin/cp ${exlib_home}/examples/cpp/pack_README ${to}/README
#fi

find ${to}/ourex -name 'CVS' -print > tmp_0
for file in $(cat tmp_0) ; do /bin/rm -R -f ${file}; done
/bin/rm -f tmp_0

find ${to}/ourex -name '.git' -print > tmp_0
for file in $(cat tmp_0) ; do /bin/rm -R -f ${file}; done
/bin/rm -f tmp_0

find ${to} -name 'err_log' -print > tmp_0
for file in $(cat tmp_0) ; do /bin/rm -R -f ${file}; done
/bin/rm -f tmp_0

find ${to} -name 'out_log' -print > tmp_0
for file in $(cat tmp_0) ; do /bin/rm -R -f ${file}; done
/bin/rm -f tmp_0

cd ${exlib_home}/mgr
version=`${bush_home}/app_vers`

/bin/mkdir -p ${to}/inexlib
/bin/mv ${to}/inlib ${to}/inexlib/.
/bin/mv ${to}/exlib ${to}/inexlib/.
/bin/mv ${to}/ourex ${to}/inexlib/.

cd /tmp

/bin/rm -f ./${pack_name}_source-${version}.zip
zip -qr ./${pack_name}_source-${version}.zip ${pack_name}

cd ${save_dir}
